### PR TITLE
Fix for defect 116472

### PR DESCRIPTION
**Pull request by bsanaei**

### CODE REVIEW

**Comment by jgarcows** [comment]
It breaks when you have different number of digits.  So going from 9 to 10 for example sorts it wrong.  See my test below:

```
$ IMAGES_ARRAY_NOT_USED=( jgarcows_1 jgarcows_4 jgarcows_30 )
$ for el in "${IMAGES_ARRAY_NOT_USED[@]}"; do echo "$el";  done | sort
jgarcows_1
jgarcows_30
jgarcows_4
```

**Comment by jgarcows** [comment]
It looks like you can use the following, which will sort numerically, on the second field, delimited by the colon.

`sort -t":" -k2 -n`

**Comment by bsanaei** [comment]
I provided the changes based on the comments

**Comment by jgarcows** [comment]
+1

**Pull request merged**
